name: testga
on: [push]
jobs:
  check-release:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: apt install lsb-release
      - run: lsb-release -a
